#ToDo's

[X] Add materialize-css
[X] Make materialize-css sass configurable with variables and color plattern
[X] Add google design icons with npm
[X] Add config mgmt
[X] Add logging system
[X] Animation
[X] Layout Wrapper
[X] Remove Bootstrap
[X] Add bootstrap manual to the readme
[X] Add all important libs like moment, lodash ...
[ ] Add custome attribute example
[ ] Add service example
[X] Add cordova
[ ] Add cordova docu and helpers and stuff
[X] Add travis
[ ] Add greenkeeper